### PR TITLE
Fix crash when double underscore '__' is in param name

### PR DESCRIPTION
**Pull request by JeyRunner**

### CODE REVIEW

**Review by LiXiling — CHANGES_REQUESTED** [review]
This is a bug I did not think about. Could you please add a code comment, so I don't forget and remove it in the future?

**Comment by LiXiling** [comment]
Thanks for the fix. Could you please just add a short comment. Then I will merge the fix :)

**Comment by JeyRunner** [comment]
I added a comment :)

**Review by LiXiling — APPROVED** [review]
Thank you very much for your contribution. I will release a new version on Pypi momentarily

**Pull request merged**
